## A basic GitHub Actions workflow for your Quarkus application.

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Test Coverage
        run: ./gradlew test
      - name: Build Native
        run: ./gradlew build -Dquarkus.package.type=native
        
      
